### ISSUE TITLE
objectHovered method is not working 

### ISSUE THREAD

**Issue by 24thdiv** [Netflix/vizceral-react#11]
Hi, I am using this react component and I used objectHovered method but it's not working. I am using this event for regional nodes. objectHighlighted method is working though. Here is my code: 
```

class App extends Component {

   constructor() {
      super();
       this.state={
          trafficData:nodes,
          allowDraggingOfNodes:true
        }
        this.objectHighlighted.bind(this);
        this.objectHovered.bind(this);
   }

   objectHighlighted(data){
    console.log(data);
   }
   objectHovered(data){
    console.log(data);
   }
  render() {
    console.log(this.state.trafficData);
    return (
      <div className="App" style={{height:800}}>
        <Vizceral traffic={this.state.trafficData}
                  allowDraggingOfNodes={this.state.allowDraggingOfNodes}
                  objectHighlighted={this.objectHighlighted}
                  objectHovered={this.objectHovered}
                  
        />

      </div>
    );
  }
}
```

**Comment by aSqrd-eSqrd** [comment]
It doesn't work, because it isn't "wired up" in `vizceral-react/src/vizceral.jsx`.   It exist in `vizceral/src/vizceral.js`.  The "wiring" is just missing from `vizceral-react`.  It looks like it should be easy to patch up by mimicking the the event setup for `objectHighlighted` [here (lines 61-66)](https://github.com/Netflix/vizceral-react/blob/master/src/vizceral.jsx#L61)  and then down at the bottom it probably should be added to the `Vizceral.defaultProps`.

@jrsquared, I've noticed that there is some disparity between things in the `propTypes`  object, the `defaultProps` object, and the actual `this.props` used.  Then there is the orphaned `objectHovered` [event ](https://github.com/Netflix/vizceral/blob/4575276f261e90de78f29a3d6987298eced1bc53/src/vizceral.js#L40).  I made a little table of who occurs where for the events and props, but it needs someone more knowledgeable of the whole system to "synchronize" it all.

prop/event |  IN `defaultProps` | IN `propTypes` | IN `this.props`
-----|--------------------|--------------|-------
allowDraggingOfNodes | yes | yes | yes
connectionHighlighted | yes | yes | **NO**
definitions | yes | yes | yes
filters | yes | yes | yes
match | yes | yes | yes
matchesFound | yes | yes | yes
modes | **NO** | yes | yes
nodeContextSizeChanged | yes | yes | yes
nodeHighlighted | yes | yes | **NO**
nodeUpdated | yes | **NO** | yes
objecHighlighted | yes | **NO** | yes
objectHovered | **NO** | **NO** | **NO**
objectToHighlight | **NO** | **NO** | yes
showLabels | yes | yes | yes
styles | yes | yes | yes
targetFramerate | yes | yes
traffic | yes | yes | yes
view | yes | **NO** | yes
viewChanged | yes | yes | yes
viewUpdated | yes | yes | yes

**Comment by 24thdiv** [comment]
Hi , I tried with mimicking the the event setup for objectHighlighted. Still doesn't work.

**Comment by jsamireddy** [comment]
I have created this pr https://github.com/Netflix/vizceral/pull/129 which has fixed the issue for me on the sandbox.

**Comment by jrsquared** [comment]
Merged the PR and released a new version. Thank you @jsamireddy !
