### ISSUE TITLE
Layout is reset when this.state.trafficData is set

### ISSUE THREAD

**Issue by voelzmo** [Netflix/vizceral-react#8]
It seems that the layout is reset when updated traffic data is set on `this.state.trafficData`, even when dragging of nodes is enabled and the set of nodes in the trafficData didn't change.

I would understand resetting the layout, if the set of nodes changes and a human didn't move the nodes around.

What do you think? Is dragging nodes really incompatible with continuously updating traffic data, or am I doing it wrong?

**Comment by voelzmo** [comment]
Additional note: the effect is even there when I don't drag around nodes. The layout can seems to change pretty randomly after a traffic data update.

**Comment by jrsquared** [comment]
Every time data is updated the layout gets recalcuated. That being said, layout is deterministic, so if you send the same layout with the same connection data, it should all stay in the same place. If you are dropping/adding connections or some connections, then it will try to recalculate. If you can give a simple example of a few data sets that when switching between them it causes a relayout, I can take a look.

**Comment by maxio89** [comment]
Are you sure that layout is recalculated when new connection are added or some other data are changed, because it doesn't work like that in my case.
I need to manually change the view or refresh the whole page to be able to see any change, e.g. new connections.
I'm using this app:
https://github.com/Netflix/vizceral-example
